# GMIT
# HD Computer Science - Data Analytics
# Programming for Data Analytics - Project 2018

about the project

chosen problem: OBESITY

In Ireland 60% of adults are overweight (excess weight or obese) [1]. Besides, the prevalence of excess weight/obesity in adults from 18 to 64 years in Ireland has increased since 1990. Therefore, it still is a major public health problem in Ireland [2].
It's estimated that an adult woman needs 1600 to 2400 calories per day and it depends on a number of factors, such as age, height, weight and level of physical activity. So, the low end of the calories needed per day is for sedentary women and the higher end of the range is for the active women [3].
It is well known that to maintain a healthy weight the amount of calories consumed must be in balance with the amount of calories burnt. Therefore, the amount of calories consumed must be greater than the calories burnt to result in  a gain weight [4].
It is no wonder that  the average daily consumption of calories in Ireland is 2307 calories. The world  average daily consumption of calories is 1398. So, come as no surprise that the average daily energy consumption of calories in Ireland it is one of the biggest in the world [5]. 

The database that will be created includes only overweight and obese adult women in Ireland. The variables chosen are: 

1.  Age
2. Height 
3. Weight 
4. Energy intake per day 

Age: the average age of adults in Ireland is 37.4 years [6].  

Height: the average height in women aged from 20 to 49 years in Ireland is 1.63m [2, 7].

Weight: the average weight in women in Ireland is 69.926 / 70kg [2, 8]. 

<img src="https://image.ibb.co/kSvBx0/2018-11-19-21-53-22-NATIONAL-ADULT-NUTRITION-SURVEY.png" alt="2018-11-19-21-53-22-NATIONAL-ADULT-NUTRITION-SURVEY" border="0"> Anthropometric measurements (mean values) for men and women by age group [2]


But based on the height I've calculated the BMI to get a minimum weight classified as overweight and the maximum to be classified as obese. In fact, there is no maximum weight to be obese, but it was considered a BMI of superobesity (50kg/m2). The World Health Organisation (WHO) BMI cut-off points were used to estimate the weight. The BMI (Quetelet index) indicates the nutritional status in adults and it's a measure defined as the weight (in kilograms) divided by the square of height (in metres) [9].
The National Adult Nutrition Survey in 2011 with a 1500 adults (740 men and 760 women) showed that among 18 to 64 years old women a total of 21% were obese and 31% were overweight [2]. The Survey of Lifestyle, Attitudes and Nutrition (SLÁN) in 2007 with 10000 adults in Ireland showed that 33% women were overweight and 25% of them were obese [10].


<img src=https://ibb.co/kNLVPf border="0"> BMI formula


<img src="https://image.ibb.co/dAWC4f/WHO-Europe-Nutrition-Body-mass-index-BMI.png" alt="WHO-Europe-Nutrition-Body-mass-index-BMI" border="0"> BMI nutritional status

<img src="https://image.ibb.co/dP2PH0/SLAN-2007-Survey-of-Lifestyle-Attitudes-Nutrition-in-Ireland-Main-Report.png" alt="SLAN-2007-Survey-of-Lifestyle-Attitudes-Nutrition-in-Ireland-Main-Report" border="0"> Self-reported BMI scores for women, by age SLAN 2007

<img src="https://image.ibb.co/kwJ9jf/2018-11-19-21-57-06-NATIONAL-ADULT-NUTRITION-SURVEY.png" alt="2018-11-19-21-57-06-NATIONAL-ADULT-NUTRITION-SURVEY" border="0">  Percent men and women in each age group in each of the BMI categories from the NANS 2011

Energy intake per day: the average consumption of calories in Ireland is 2307 [5].

In [1]:
# 1000 women: 48% healthy weight, 31% overweight, 21% obese
# 480 healthy weight
# 310 overweight
# 210 obese
# total of 520 overweight/obese

# Calculate weight (min and max) of the sample

# Square of height (in m)
h = 1.63

h2 = h * h

h2

2.6569

In [2]:
# overweight - BMI greater or equal 25kg/m2 
min_bmi = 25

min_weight = h2 * min_bmi

min_weight

66.4225

In [3]:
# superobesity - BMI greater or equal 50kg/

max_bmi = 50

max_weight = h2 * max_bmi

max_weight

132.845

In [4]:
# Import libraries

import numpy as np

In [5]:
# Generate random height

height= np.random.normal(1.63, 0.01, 520)

height

array([ 1.62601433,  1.63142416,  1.62302697,  1.63187906,  1.63964661,
        1.62087868,  1.64721712,  1.62905568,  1.6301792 ,  1.63076866,
        1.62682114,  1.61281144,  1.62935895,  1.63547134,  1.62995495,
        1.62857014,  1.63250499,  1.62657425,  1.64652288,  1.64261173,
        1.63567491,  1.63717978,  1.63560055,  1.645018  ,  1.62278896,
        1.63861715,  1.60516285,  1.64922064,  1.61786406,  1.64185687,
        1.60448945,  1.64489358,  1.63193627,  1.63456963,  1.62970021,
        1.62695919,  1.63720591,  1.6262154 ,  1.63219176,  1.64179934,
        1.63206851,  1.61192625,  1.62805533,  1.61393461,  1.62846599,
        1.63031162,  1.61843306,  1.64080861,  1.63777226,  1.6461822 ,
        1.6189921 ,  1.63648969,  1.63310395,  1.65207509,  1.63890536,
        1.63402384,  1.62990993,  1.65375001,  1.63038321,  1.63304553,
        1.62631219,  1.64096497,  1.6281855 ,  1.63988654,  1.6203361 ,
        1.62567173,  1.61898725,  1.61491493,  1.62522954,  1.63

In [ ]:
# Height - Plot


In [6]:
# Generate random weight

weight = np.random.randint(66.4225, 132.9, 520)

weight

array([128,  91, 131, 125,  99, 101,  70,  73, 101,  92, 106,  76, 109,
        74, 108, 113, 108, 120,  94, 125, 116, 114,  84,  68,  88,  99,
        87,  84,  82, 128, 129,  89,  79,  79,  69,  84, 120,  85,  98,
        78, 101,  78,  78, 102, 122,  90,  68, 120,  97,  83, 109,  73,
       101, 129, 105, 113,  66, 103, 104,  72, 129, 122,  83,  83,  77,
        83, 129, 112, 115,  81,  85, 102,  84,  97,  66, 123, 100, 104,
        89,  74,  92, 122, 119, 109, 115,  67,  90, 109,  90, 105,  91,
        94,  83,  95,  89,  90,  78, 101, 125,  70,  97, 107,  78,  76,
       117,  74,  79,  71,  97, 124, 100,  90, 107, 118,  80,  74,  67,
       117, 114, 127, 114, 113, 108,  78, 107, 124,  93, 118,  99,  71,
        99,  67,  71, 117, 108,  85,  98, 126,  74, 106,  74, 114, 116,
        76, 125,  81,  90, 100,  90,  67,  92,  69,  86, 110,  71, 113,
        69,  84,  87,  77, 110, 114, 105,  90,  69,  93, 108,  79,  74,
        78, 110,  93, 121,  74, 130,  94,  80, 119,  92, 103,  9

In [ ]:
# Weight - Plot


In [7]:
# Calculate BMI of the sample

h2 = height * height

h2

array([ 2.64392259,  2.66154481,  2.63421655,  2.66302927,  2.68844102,
        2.62724768,  2.71332424,  2.65382241,  2.65748423,  2.65940642,
        2.64654701,  2.60116073,  2.6548106 ,  2.67476649,  2.65675313,
        2.6522407 ,  2.66507256,  2.6457438 ,  2.71103761,  2.6981733 ,
        2.67543242,  2.68035763,  2.67518917,  2.70608423,  2.633444  ,
        2.68506617,  2.57654779,  2.7199287 ,  2.61748412,  2.69569399,
        2.57438639,  2.70567488,  2.66321599,  2.67181789,  2.65592279,
        2.64699619,  2.68044321,  2.64457653,  2.66404994,  2.69550506,
        2.66364763,  2.59830622,  2.65056414,  2.60478491,  2.65190149,
        2.65791597,  2.61932558,  2.6922529 ,  2.68229798,  2.70991582,
        2.62113541,  2.67809849,  2.6670285 ,  2.72935211,  2.68601079,
        2.67003392,  2.65660639,  2.73488909,  2.65814942,  2.66683769,
        2.64489134,  2.69276604,  2.65098802,  2.68922786,  2.62548908,
        2.64280856,  2.62111971,  2.60795023,  2.64137105,  2.68

In [8]:
bmi = weight/h2

bmi

array([ 48.41291523,  34.19066995,  49.73015602,  46.93902593,
        36.82431537,  38.44327305,  25.79861226,  27.50749244,
        38.00586998,  34.59418588,  40.05218861,  29.21772543,
        41.05754291,  27.66596646,  40.65112361,  42.60548444,
        40.524225  ,  45.35586559,  34.67307118,  46.32763954,
        43.35747707,  42.53163778,  31.39964865,  25.12855998,
        33.41631725,  36.87059974,  33.76611157,  30.88316245,
        31.32779276,  47.4831344 ,  50.10902817,  32.89382645,
        29.66338458,  29.56788351,  25.97967092,  31.73408416,
        44.76871575,  32.14125176,  36.78609718,  28.93706309,
        37.91792841,  30.0195563 ,  29.42769756,  39.15870345,
        46.00472551,  33.86111565,  25.96088117,  44.57233566,
        36.16302162,  30.62825768,  41.58503199,  27.25814611,
        37.86986156,  47.26396404,  39.09142903,  42.32155973,
        24.84372555,  37.6614907 ,  39.12496389,  26.99826852,
        48.77327023,  45.30657251,  31.30908154,  30.86

In [ ]:
# Plot - BMI



In [9]:
# Number of overweight

overweight = ov ("filtrar" mulheres com BMI entre 25 e 29.999)


In [10]:
# Number of obese

obese = ob ("filtrar" mulheres com BMI igual ou maior a 30)

obese_1 = ob1 (mulheres com BMI igual a 30 e 34.999)

obese_2 = ob2 (mulheres com BMI entre 35 e 39.999)

obese_3_superobese = ob3 (mulheres com BMI entre 40 e 49.999)

super_obese = superob (mulheres com BMI maior ou igual a 50)


In [11]:
# Generate daily energy intake

energy_intake = np.random.normal (2307, 500, 520)

energy_intake

array([ 3024.05411878,  1526.15042867,  2521.94079189,  2216.54015814,
        1802.85666572,  1663.80598421,  2520.34630747,  2879.42624178,
        1755.63896594,  1767.38247636,  2145.91026981,  2299.76408078,
        2364.6245826 ,  2082.35084565,  2365.29708254,  2329.40246567,
        2618.67783646,  2133.23895173,  1678.82041181,  1411.10130416,
        2593.44730549,  2144.25833449,  2119.74620642,  2361.49391893,
        2412.80611706,  2094.79956012,  3157.28703817,  2577.0927846 ,
        2349.5556886 ,  1578.04547608,  2955.2664591 ,  2670.35688107,
        2677.98659961,  2962.01768705,  2088.3582632 ,  1921.13814786,
        2710.09705394,  2554.95838351,  2579.64440168,  3092.16559619,
        2910.81920495,  2582.08216126,  1492.87033686,  2212.66428161,
        3633.03481665,  2031.86439708,  1118.62559131,  2135.57406373,
        2201.54210321,  2636.01330974,  2451.77425548,  2215.23199786,
        2643.93335617,  2799.45178581,  2988.8804197 ,  2112.74646402,
      

In [ ]:
# Daily Energy Intake - Plot


In [ ]:
# Create group based on nutritional status (BMI)

overweight = ov

obese = ob

# Plot 2 groups x daily energy intake


# Plot 2 groups x age


References
1. https://www.safefood.eu/SafeFood/media/SafeFoodLibrary/Documents/Professional/Nutrition/Adult-and-children-obesity-trends-ROI.pdf
2.   https://irp-cdn.multiscreensite.com/46a7ad27/files/uploaded/The%20National%20Adult%20Nutrition%20Survey%20Summary%20Report%20March%202011.pdf
3 https://health.gov/dietaryguidelines/2015/guidelines/appendix-2/
4. https://www.nhs.uk/common-health-questions/food-and-diet/what-should-my-daily-intake-of-calories-be/
5. https://www.irishexaminer.com/ireland/irish-among-the-biggest-consumers-of-calories-per-day-428077.html
6. https://www.cso.ie/en/csolatestnews/pressreleases/2017pressreleases/pressstatementcensus2016resultsprofile3-anageprofileofireland/
7. https://en.wikipedia.org/wiki/List_of_average_human_height_worldwide
8. https://en.wikipedia.org/wiki/Human_body_weight
9. http://www.euro.who.int/en/health-topics/disease-prevention/nutrition/a-healthy-lifestyle/body-mass-index-bmi
10. https://epubs.rcsi.ie/cgi/viewcontent.cgi?article=1002&context=psycholrep
